# Generated by Django 4.1 on 2022-08-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OpenTASite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subdomain", models.CharField(max_length=4096)),
                ("db_name", models.CharField(max_length=4096)),
                ("db_label", models.CharField(default="", max_length=4096)),
                ("creator", models.CharField(default="", max_length=4096)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("data", models.JSONField(default=dict)),
            ],
        ),
        migrations.AddConstraint(
            model_name="opentasite",
            constraint=models.UniqueConstraint(
                fields=("db_name",), name="Database must be unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="opentasite",
            constraint=models.UniqueConstraint(
                fields=("subdomain",), name="Subdomain value must be unique"
            ),
        ),
    ]
