# Generated by Django 3.1.5 on 2022-09-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opentasites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opentasite',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
